# Generated by Django 5.1.1 on 2025-05-23 15:40
from django.db import migrations

def create_initial_institutions(apps, schema_editor):
    Institution = apps.get_model('api', 'Institution')
    Institution.objects.bulk_create([
        Institution(name="МГУ"),
        Institution(name="СПбГУ"),
        Institution(name="НГУ"),
    ])

class Migration(migrations.Migration):
    dependencies = [
        # Укажите последнюю миграцию вашего приложения
        ('api', '0004_institution_application_institution'),
    ]
    
    operations = [
        migrations.RunPython(create_initial_institutions),
    ]

